### ISSUE TITLE
Token regen

### ISSUE THREAD

**Issue by himynamesned** [dburkland/ios_shortcuts#5]
Suggest modifying read me to suggest utilising shortcut automation. (Instead of iOS reminder) I’ve set mine to to run regen shortcut automatically 00:00 1st every month.

**Comment by dburkland** [comment]
Hello @himynamesned and thanks for creating this issue. I have since updated the "Generate Tesla Token" shortcut in my "tesla_ios_shortcuts" repo to support automations and also included some documentation on how to set it up in iOS 14. For more details see the following [link](https://github.com/dburkland/tesla_ios_shortcuts/blob/master/README.md).

Cheers,

Dan
